---
# tasks file for nextcloud-setup
#
- name: Extact nextcloud-29.0.7.tar.bz2 into storage directory
  ansible.builtin.unarchive:
    src: nextcloud-29.0.7.tar.bz2
    dest: /storage/webserver
  when: (ansible_hostname == "storage")

- name: change nextcloud files' owner
  ansible.builtin.file:
    path: /storage/webserver
    state: directory
    recurse: yes
    owner: www-data
    group: www-data


