---
# handlers file for webserver2

- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: enable nextcloud vhost
  ansible.builtin.shell: /usr/sbin/a2ensite nextcloud.conf


