---
# handlers file for dbmaster

- name: flush privileges
  command: mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES"

- name: restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
