---
# handlers file for logserver

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
