---
# tasks file for logserver

- name: Set timezone to Europe/Moscow
  become: yes
  community.general.timezone:
    name: Europe/Moscow

- name: edit rsyslog config
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
  notify: restart rsyslog

- name: install zabbix-agent
  tags: install_zabbix_agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
    update_cache: true

- name: import zabbix-agent config
  tags: install_zabbix_agent
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

- name: import logrotate config
  tags: import_logrotate_config
  ansible.builtin.template:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
  with_items:
    - { s: "logrotate.httplogs", d: "/etc/logrotate.d/httplogs" }
    - { s: "logrotate.rsyslog", d: "/etc/logrotate.d/rsyslog" }

